### ISSUE TITLE
We called Double DQN (2015) as DDQN. Dueling DQN (2016) be called as DUEL

### ISSUE THREAD

**Issue by Yonv1943** [gouxiangchen/dueling-DQN-pytorch#2]
**Your code is really good. It deserves more stars.**  
I try your code in other gym environment and it train faster than other Dueling DQN implement.

Besides, I'm confuse with the name of `ddqn.py`.
Then I know that in here, `ddqn.py` means Dueling DQN instead of Double DQN.

Even in paper "**Dueling Network** Architectures for Deep Reinforcement Learning".
They call Double DQN as "DDQN", and call Dueling DQN as "DUEL". See paper Table. 2.

**Comment by gouxiangchen** [comment]
Thank you for your suggestion. In fact in my ddqn implementation, Double DQN is also involved. See [ddqn.py, 131 ~ 135 lines](https://github.com/gouxiangchen/dueling-DQN-pytorch/blob/master/ddqn.py).

Maybe I should call it dueling DDQN. How about naming it as `d3qn.py`  :joy:

**Comment by gouxiangchen** [comment]
I realize that authors also used double dqn in the dueling dqn paper. The name "dueling dqn" may include double dqn implicitly. Therefore I rename `ddqn.py` to `dueling_dqn.py` in this repo.

Hope it is clear now, thank you very much.

**Comment by Yonv1943** [comment]
Thank you for your reply.  My question has been solved. I will closed this "Issue".
